name: CI/CD Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Collect Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for git describe to work correctly

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Build All Platforms
        run: make build

      - name: Build Debian Package
        run: make deb

      - name: List Build Artifacts
        run: find build -type f

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnsleaktest-release-builds
          path: build/
          retention-days: 5

